package:
  name: illumiprocessor
  version: 2.0.7

source:
  fn: v2.0.7.tar.gz
  url: https://github.com/faircloth-lab/illumiprocessor/archive/v2.0.7.tar.gz
  sha1: 337385bccf0a0e8b2bc844714153831485229979

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - trimmomatic

test:
    commands:
      - illumiprocessor --help

about:
  home: https://github.com/faircloth-lab/illumiprocessor
  license: BSD
