package:
  name: pyvcf
  version: !!str 0.6.4

source:
  fn: PyVCF-0.6.4.tar.gz
  url: https://pypi.python.org/packages/source/P/PyVCF/PyVCF-0.6.4.tar.gz
  md5: fc9a0668076ebe45afdd8a0d74dc7711

build:
  number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python

test:
  # Python imports
  imports:
    - vcf.test
    - vcf

about:
  home: https://github.com/jamescasbon/PyVCF
  license: BSD
