package:
    name: raxml
    version: !!str 8.0.19

source:
# The source section specifies where the source code of the package is coming
# from, it may be coming from a source tarball like:
    git_url: https://github.com/stamatak/standard-RAxML.git
    git_tag: v8.0.19

# The build number should be incremented for new builds of the same version
build:              # (optional)
    number: 0       # (optional, defaults to 0)

test:
# commands we want to make sure they work, which are expected to get installed
# by the package
    commands:
        - raxmlHPC-PTHREADS-SSE3 -v
        - raxmlHPC-SSE3 -v

about:
    home: http://www.exelixis-lab.org/
    license: GPL
