package:
  name: jellyfish
  version: !!str 0.2.0

source:
  fn: jellyfish-0.2.0.tar.gz
  url: https://pypi.python.org/packages/source/j/jellyfish/jellyfish-0.2.0.tar.gz
  md5: 8f5d27bddd8986408f7004814982b202

build:
  number: 2

requirements:
  build:
    - python
    - distribute

  run:
    - python
    - distribute

test:
  # Python imports
  imports:
    - jellyfish

about:
  home: http://github.com/sunlightlabs/jellyfish
  license: BSD License
