package:
  name: cookiecutter
  version: !!str 0.7.2

source:
  fn: cookiecutter-0.7.2.tar.gz
  url: https://pypi.python.org/packages/source/c/cookiecutter/cookiecutter-0.7.2.tar.gz
  md5: 9201ca32ddd8e3ad4e43f8d822e78371
#  patches:
   # List any patch files here
   # - fix.patch

build:
  #preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cookiecutter = cookiecutter:main
    #
    # Would create an entry point called cookiecutter that calls cookiecutter.main()

    - cookiecutter = cookiecutter.main:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - binaryornot
    - jinja2
    - pyyaml

  run:
    - python
    - binaryornot
    - jinja2
    - pyyaml

test:
  # Python imports
  imports:
    - cookiecutter

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - cookiecutter --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/audreyr/cookiecutter
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
