package:
    name: samtools
    version: !!str 0.1.19

source:
    fn: samtools-0.1.19.tar.bz2
    url: http://downloads.sourceforge.net/project/samtools/samtools/0.1.19/samtools-0.1.19.tar.bz2
    sha1: ff3f4cf40612d4c2ad26e6fcbfa5f8af84cbe881

build:
    number: 2

about:
    home: http://samtools.sourceforge.net/
    license: MIT
