package:
    name: mrbayes      # lower case name of package, may contain '-' but no spaces
    version: 3.2.2     # version of package. Should use the PEP-386 verlib conventions.

source:
# The source section specifies where the source code of the package is coming
# from, it may be coming from a source tarball like:
    fn: mrbayes-3.2.2.tar.gz
    url: http://downloads.sourceforge.net/project/mrbayes/mrbayes/3.2.2/mrbayes-3.2.2.tar.gz
    sha1: 6f469f595a3dbd2f8394cb29bc70ca1773338ac8

# The build number should be incremented for new builds of the same version
build:              # (optional)
    number: 0       # (optional, defaults to 0)

# tests are in run_test.py

about:
    home: http://mrbayes.sourceforge.net/download.php
    license: GPL
