package:
    name: mrbayes
    version: !!str 3.2.2

source:
    fn: mrbayes-3.2.2.tar.gz
    url: http://downloads.sourceforge.net/project/mrbayes/mrbayes/3.2.2/mrbayes-3.2.2.tar.gz
    sha1: 6f469f595a3dbd2f8394cb29bc70ca1773338ac8

build:
    number: 1

# tests are in run_test.py

about:
    home: http://mrbayes.sourceforge.net/download.php
    license: GPL
