package:
    name: mccabe
    version: 0.2.1

source:
    fn: mccabe-0.2.1.tar.gz
    url: https://pypi.python.org/packages/source/m/mccabe/mccabe-0.2.1.tar.gz
    md5: 5a3f3fa6a4bad126c88aaaa7dab682f5

build:
    entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - mccabe = mccabe:main
    #
    # Would create an entry point called mccabe that calls mccabe.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python

test:
  # Python imports
  imports:
    - mccabe

about:
  home: https://github.com/flintwork/mccabe
  license: MIT License
