package:
  name: binaryornot
  version: !!str 0.2.0

source:
  fn: binaryornot-0.2.0.tar.gz
  url: https://pypi.python.org/packages/source/b/binaryornot/binaryornot-0.2.0.tar.gz
  md5: ecbb411e281f3d922112c5d91f575e06
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - binaryornot = binaryornot:main
    #
    # Would create an entry point called binaryornot that calls binaryornot.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - binaryornot

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/audreyr/binaryornot
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
