package:
    name: velvet        # lower case name of package, may contain '-' but no spaces
    version: 1.2.10     # version of package. Should use the PEP-386 verlib conventions.

source:
# The source section specifies where the source code of the package is coming
# from, it may be coming from a source tarball like:
    fn: velvet_1.2.10.tgz
    url: http://www.ebi.ac.uk/~zerbino/velvet/velvet_1.2.10.tgz
    patches:
            - osx-makefile.patch [osx]
            - linux-makefile.patch [linux32 and linux64]

# The build number should be incremented for new builds of the same version
build:              # (optional)
    number: 1       # (optional, defaults to 0)

test:
# commands we want to make sure they work, which are expected to get installed
# by the package
    commands:
        - velveth --help
        - velvetg --help

about:
    home: http://www.ebi.ac.uk/~zerbino/velvet/
    license: GPL
