package:
    name: velvet
    version: !!str 1.2.10

source:
    fn: velvet_1.2.10.tgz
    url: http://www.ebi.ac.uk/~zerbino/velvet/velvet_1.2.10.tgz
    md5: 6e28c4b9bedc5f7ab2b947e7266a02f6
    patches:
        - osx-makefile.patch [osx]
        - linux-makefile.patch [linux32 and linux64]

build:
    number: 2

test:
    commands:
        - velveth --help
        - velvetg --help

about:
    home: http://www.ebi.ac.uk/~zerbino/velvet/
    license: GPL
