package:
  name: python-levenshtein
  version: !!str 0.10.2

source:
  fn: python-Levenshtein-0.10.2.tar.gz
  url: https://pypi.python.org/packages/source/p/python-Levenshtein/python-Levenshtein-0.10.2.tar.gz
  md5: c8af7296dc640abdf511614ee677bbb8

build:
  number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python

test:
  imports:
    - Levenshtein

about:
  home: http://github.com/miohtama/python-Levenshtein
  license: GPL
