package:
  name: bx-python
  version: !!str 0.7.1

source:
  fn: bx-python-0.7.1.tar.gz
  url: https://pypi.python.org/packages/source/b/bx-python/bx-python-0.7.1.tar.gz
  md5: cf26790ae22a691e40c80aa351d6dd16
  patches:
    - setup.patch

build:
  number: 2

requirements:
  build:
    - python
    - distribute
    - nose
    - numpy

  run:
    - python
    - numpy

test:
  # Python imports
  imports:
    - bx.align.sitemask
    - bx.tabular
    - bx.intervals
    - bx.align
    - bx.bbi
    - bx.cookbook
    - bx.arrays
    - bx.motif.io
    - bx.seq
    - bx.intervals.operations
    - bx.pwm
    - bx.misc
    - bx.motif
    - bx.phylo
    - bx.motif.logo
    - bx_extras
    - bx.align.tools
    - bx
    - bx.intseq

  requires:
    # Put any additional test requirements here.  For example
    - nose

about:
  home: http://bitbucket.org/james_taylor/bx-python/wiki/Home
  license:

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
