package:
    name: muscle
    version: !!str 3.8.31

source:
    fn: muscle3.8.31_src.tar.gz
    url: http://www.drive5.com/muscle/downloads3.8.31/muscle3.8.31_src.tar.gz
    sha1: 2fe55db73ff4e7ac6d4ca692f8f213d1c5071dac


build:
    number: 1

test:
    commands:
        - muscle

about:
    home: http://www.drive5.com/muscle/
    license: Public Domain
