package:
  name: dendropy
  version: !!str 3.12.1

source:
  fn: v3.12.1.tar.gz
  url: https://github.com/jeetsukumaran/DendroPy/archive/v3.12.1.tar.gz
  sha1: eeef5219d06994a1c51903c63d639a1229a1661d
  patches:
   # List any patch files here
   - setup.patch

build:
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - dendropy = dendropy:main
    #
    # Would create an entry point called dendropy that calls dendropy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - dendropy.dataio
    - dendropy
    - dendropy.test
    - dendropy.dataobject
    - dendropy.utility
    - dendropy.test.support
    - dendropy.interop
    - dendropy
    - dendropy.mathlib

  commands:
    - sumtrees.py -h
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://packages.python.org/DendroPy/
  license: BSD License
