package:
  name: phyluce
  version: !!str 1.5

source:
  git_url: https://github.com/faircloth-lab/phyluce/
  git_tag: v1.5

build:
  number: 0

requirements:
  build:
    - python

  run:
    - abyss 1.3.7
    - bedtools 2.18.1
    - biopython 1.63
    - bowtie 1.1.1
    - bwa 0.7.7
    - bx-python 0.7.1
    - dendropy 3.12.0
    - gatk-lite 2.3.0
    - gblocks 0.91b
    - illumiprocessor 2.0.7
    - lastz 1.02.00
    - mafft 7.130
    - muscle 3.8.31
    - pandas
    - picard 1.106
    - python
    - pysam 0.7.7
    - pyvcf 0.6.4
    - raxml 8.0.19
    - samtools 0.1.19
    - trinity 2.0.6
    - velvet 1.2.10

test:
# commands we want to make sure they work, which are expected to get installed
# by the package
    commands:
        - phyluce_assembly_match_contigs_to_probes --help
        - phyluce_assembly_get_match_counts --help
        - phyluce_assembly_get_fastas_from_match_counts --help
        - phyluce_align_seqcap_align --help
        - phyluce_align_get_align_summary_data --help
        - phyluce_align_format_nexus_files_for_raxml --help
    imports:
      - phyluce

about:
  summary: software for UCE (and general) phylogenomics
  home: https://github.com/faircloth-lab/phyluce/
  license: BSD
