package:
  name: phyluce
  version: 2.0.0b

source:
  fn: v2.0.0b.tar.gz
  url: https://github.com/faircloth-lab/phyluce/archive/v2.0.0b.tar.gz
  sha1: 6cc7e7b3218c13b70173f9685e006c980b7e6757

build:
  number: 0

requirements:
  build:
    - python

  run:
    - abyss
    - bedtools
    - biopython
    - bwa
    - bx-python
    - dendropy
    - gatk-lite
    - illumiprocessor
    - lastz
    - mafft
    - muscle
    - picard
    - python
    - pysam
    - pyvcf
    - raxml
    - samtools
    - velvet

about:
  home: https://github.com/faircloth-lab/phyluce/
  license: BSD
