package:
  name: phyluce
  version: !!str 2.0.0

source:
  git_url: https://github.com/faircloth-lab/phyluce/
  git_tag: working

build:
  number: 0

requirements:
  build:
    - python

  run:
    - abyss 1.3.7
    - bedtools 2.18.1
    - biopython 1.63
    - bwa 0.7.7
    - bx-python 0.7.1
    - dendropy 3.12.0
    - gatk-lite 2.3.0
    - illumiprocessor 2.0.7
    - lastz 1.02.00
    - mafft 7.130
    - muscle 3.8.31
    - picard 1.106
    - python
    - pysam 0.7.7
    - pyvcf 0.6.4
    - raxml 8.0.19
    - samtools 0.1.19
    - velvet 1.2.10

about:
  home: https://github.com/faircloth-lab/phyluce/
  license: BSD
