package:
  name: phyluce
  version: 2.0.0-working

source:
  git_url: https://github.com/faircloth-lab/phyluce/
  git_tag: working

build:
  number: 0

requirements:
  build:
    - python

  run:
    - abyss
    - bedtools
    - biopython
    - bwa
    - bx-python
    - dendropy
    - gatk-lite
    - illumiprocessor
    - lastz
    - mafft
    - muscle
    - picard
    - python
    - pysam
    - pyvcf
    - raxml
    - samtools
    - velvet

about:
  home: https://github.com/faircloth-lab/phyluce/
  license: BSD
