package:
  name: trinity         # lower case name of package, may contain '-' but no spaces
  version: !!str v2.0.6 # version of package. Should use the PEP-386 verlib conventions.

source:
# The source section specifies where the source code of the package is coming
# from, it may be coming from a source tarball like:
  fn: v2.0.6.tar.gz
  url: https://github.com/trinityrnaseq/trinityrnaseq/archive/v2.0.6.tar.gz
  sha1: b67d5d272e33265b35d4dd68cd96cb816f1ac6b8
  patches:
    - osx-makefile.patch # [osx]
    - osx-chrysalis_Makefile_g++_x86_64.patch # [osx]
    - osx-trinity-plugins.patch # [osx]
    - osx-Trinity.patch # [osx]
    - linux-Trinity.patch # [linux64]

# The build number should be incremented for new builds of the same version
build:            # (optional)
  number: 0       # (optional, defaults to 0)

about:
  home: http://trinityrnaseq.github.io/
  license: BSD
