package:
  name: pysam
  version: 0.7.7

source:
  fn: pysam-0.7.7.tar.gz
  url: https://pypi.python.org/packages/source/p/pysam/pysam-0.7.7.tar.gz
  md5: eaf9f37cbccc5e2708754d045909c1a0

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pysam = pysam:main
    #
    # Would create an entry point called pysam that calls pysam.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute
    - cython

  run:
    - python
    - distribute
    - cython

test:
  # Python imports
  imports:
    - pysam
    - pysam.include
    - pysam.include.samtools
    - pysam.include.tabix
    - pysam.include.samtools.bcftools

about:
  home: http://code.google.com/p/pysam/
  license: MIT
