package:
    name: abyss         # lower case name of package, may contain '-' but no spaces
    version: !!str 1.3.7    # version of package. Should use the PEP-386 verlib conventions.

source:
    fn: abyss-1.3.7.tar.gz
    url: http://www.bcgsc.ca/platform/bioinfo/software/abyss/releases/1.3.7/abyss-1.3.7.tar.gz
    md5: 5d34be7ae850f79b5fe06acf9fca8bc8
    # note that post-link script modified abyss-pe shebang to change make
    # to condaflmake

# The build number should be incremented for new builds of the same version
build:              # (optional)
    number: 4       # (optional, defaults to 0)

requirements:
  build:
    - boost
    - google-sparsehash

  run:
    - condaflmake

test:
# commands we want to make sure they work, which are expected to get installed
# by the package
    commands:
        - abyss-pe --help
        - ABYSS --help

about:
    home: http://www.bcgsc.ca/platform/bioinfo/software/abyss
    license: GPL
